LOCAL_PATH := $(my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := Superuser
LOCAL_SRC_FILES := me.phh.superuser.1033.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := .apk
LOCAL_BUILT_MODULE_STEM := package.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_PRIVILEGED_MODULE := true
LOCAL_PRODUCT_MODULE := true
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT_APPS)

include $(BUILD_PREBUILT)
